#!/bin/sh
# .git/hooks/pre-push

# 設定日誌檔案路徑
log_file=".git/hooks/pre-push.log"


# 定義版本遞增函數
increment_version() {
    # 版本號遞增邏輯
    version_file="version.txt"
    if [ ! -f $version_file ]; then
        echo "未找到 version.txt！創建一個新的，初始值為 1。" >> $log_file
        echo "1" > $version_file
    else
        current_version=$(cat $version_file)
        new_version=$((current_version + 1))
        echo $new_version > $version_file
        echo "版本更新至 $new_version" >> $log_file
    fi

    git add $version_file

    # 獲取當前提交的訊息
    old_commit_message=$(git log -1 --pretty=%B)
    new_commit_message="$old_commit_message 版本：$current_version 升級版本至 $new_version"

    # 修改提交，保留原訊息並添加版本遞增信息
    git commit --amend --no-edit -m "$new_commit_message"
    echo "修改提交訊息為：$new_commit_message" >> $log_file
}

# 獲取即將推送的遠端分支名稱
remote_branch=$(git rev-parse --abbrev-ref HEAD)

# 記錄分支信息到日誌
echo "正在推送至分支：$remote_branch" >> $log_file

# 檢查當前提交是否為合併提交
is_merge_commit=$(git log -1 --pretty=%P | wc -w)
merge_parents=$(git log -1 --pretty=%P)

echo "合併提交檢查結果：$is_merge_commit" >> $log_file
echo "當前提交的父節點：$merge_parents" >> $log_file

# 僅當推送到 main 分支時才處理版本號遞增
if [ "$remote_branch" == "main" ]; then
    echo "在 main 分支上，進行版本檢查..." >> $log_file

    if [ "$is_merge_commit" -eq 2 ]; then
        echo "檢測到合併提交。檢查是否應遞增版本..." >> $log_file

        # 檢查合併提交的兩個父節點，是否一個在 main，另一個不在 main
        parent1=$(echo $merge_parents | awk '{print $1}')
        parent2=$(echo $merge_parents | awk '{print $2}')

        # 確認這不是因為`rebase`或其他原因產生的合併提交
        if git merge-base --is-ancestor $parent1 origin/main && git merge-base --is-ancestor $parent2 origin/main; then
            echo "從分支檢測到合併提交，跳過版本遞增。" >> $log_file
        else
            # 檢查提交訊息中是否已經包含版本號信息
            commit_message=$(git log -1 --pretty=%B)
            if echo "$commit_message" | grep -q '升級版本至'; then
                echo "提交訊息已包含版本遞增，跳過版本遞增。" >> $log_file
            else
                echo "檢測到新的合併提交，遞增版本號..." >> $log_file
                increment_version
            fi
        fi
    else
        commit_message=$(git log -1 --pretty=%B)
        if echo "$commit_message" | grep -q '升級版本至'; then
            echo "提交訊息包含 '升級版本至'，跳過版本遞增。" >> $log_file
        else
            echo "未檢測到合併提交，遞增版本號..." >> $log_file
            increment_version
        fi
    fi

else
    echo "正在推送到 $remote_branch 分支，無需版本遞增。" >> $log_file
fi
